# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3756b7535e3b56c41cb3a5cfd7c753b5d85505ec2456b8d705877ac715ec923d43e21b24e47cf5e6dbf2de9125cbddabb5282c544b86e0844ef8902073cdd65

test:
  secret_key_base: 85ac39fc4663d4d3c2867c4dff4bc7f7fa7b383677f8ab88e1d4e0892ab4ca00155b6e440935555a503645ecf7b39234160cb7783aa7d04bb0bd7ea6109b03d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
